### ISSUE TITLE
fresh app doesn't work after `yarn eject`

### ISSUE THREAD

**Issue by xe4me** [mathieudutour/create-react-native-app-typescript#12]
`yarn eject` breaks the app : .

I followed the steps, exactly as provided in the docs.
It was working with expo, but right after I did `yarn eject`, it throw bellow error

* `npm ls react-native-scripts-ts`:react-native-scripts-ts@1.13.0
* `npm ls react-native`: react-native@0.54.0
* `npm ls expo`:empty
* `node -v`:v9.2.1
* `npm -v`:5.6.0
* `yarn --version`:v1.2.1
* `watchman version`:4.9.0

1. Operating system: Mac OS
2. Phone/emulator/simulator & version: IphoneX  Emulator , Iphone6 Emulator

<img width="293" alt="screen shot 2018-05-04 at 11 06 47 pm" src="https://user-images.githubusercontent.com/7995651/39629687-5ce44568-4ff0-11e8-81b2-e8c7e69f8d4f.png">

**Comment by Spetastian** [comment]
I have the same issue. Any updates on this?

**Comment by phoenecke** [comment]
I needed to create a file `rn-cli.config.js` as explained here: https://github.com/Microsoft/TypeScript-React-Native-Starter#adding-typescript

```
module.exports = {
  getTransformModulePath() {
    return require.resolve("react-native-typescript-transformer");
  },
  getSourceExts() {
    return ["ts", "tsx"];
  }
};```

**Comment by mathieudutour** [comment]
ah we should be able to automate that file creation in the eject script if someone wants to create a PR
