### ISSUE TITLE
When ejected a `No bundle URL present.` error crashes the build.

### ISSUE THREAD

**Issue by karloluis** [mathieudutour/create-react-native-app-typescript#3]
## Description
After successfully running the default App with Expo I tried to eject it and have it working without it. Once ejected the Build succeeded but when running `yarn run ios` (Working from a Mac Book w/ Xcode) a error pupped up.

![screen shot 2017-12-13 at 3 20 58 pm](https://user-images.githubusercontent.com/4258614/33957874-3fa03990-e019-11e7-9638-3e4886708a03.png)

![screen shot 2017-12-13 at 3 22 03 pm](https://user-images.githubusercontent.com/4258614/33957923-685687d6-e019-11e7-9e66-962d51eca467.png)

## Expected Behavior

After running `yarn run eject` I expected the `yarn run ios` build and run the default app successfully.

## Observed Behavior

The build succeeded but when running the packager/emulator errors with the `.jsbundle` where crashing.

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:  n/a
* `npm ls react-native`: 0.47.2
* `npm ls expo`: n/a
* `node -v`: 8.9.1
* `npm -v`: 5.5.1
* `yarn --version`: 1.3.2
* `watchman version`: n/a

Also specify:

1. Operating system:
2. Phone/emulator/simulator & version:

## Reproducible Demo

1. Eject generated CRNA w/ TS script.
2. Run ios script

PS noted that this might be a `react-native` related issue, but have not found a work around for either JS nor TS.

**Comment by manvesh** [comment]
Are there any fixes/workarounds for this?

**Comment by oscarCrespo** [comment]
This fixed it for me:
https://github.com/facebook/react-native/issues/12754#issuecomment-285358064

**Comment by Andraide** [comment]
You first need to start the bundler . 

In one terminal type ... npm start  (This command start the bundler )
In a second terminal type ... npx react-native run-ios 

( Or equivalents to npm and npx react-native )
