### ISSUE TITLE
No tests found after install

### ISSUE THREAD

**Issue by oskogstad** [mathieudutour/create-react-native-app-typescript#7]
Greetings!

## Description

After installing as instructed in the readme, `yarn start` runs fine. But `yarn test` results in zero tests found.

## Expected Behavior

The test to pass!

## Observed Behavior

No test found

```
yarn run v1.3.2
$ node node_modules/jest/bin/jest.js
No tests found
In /Users/skogstad/gdrive/Dev/React Native/my-app
  3 files checked.
  testMatch: **/__tests__/**/*.js?(x),**/?(*.)(spec|test).js?(x) - 0 matches
  testPathIgnorePatterns: /node_modules/ - 3 matches
Pattern:  - 0 matches
error Command failed with exit code 1.
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts-ts`: react-native-scripts-ts@1.11.3
* `npm ls react-native`: react-native@0.52.0
* `npm ls expo`: expo@25.0.0
* `node -v`: v9.5.0
* `npm -v`: 5.6.0
* `yarn --version`: 1.3.2
* `watchman version`: not installed

Also specify:

1. Operating system: 10.13.3 (17D47)
2. Phone/emulator/simulator & version: None, running tests in CLI

## Reproducible Demo
```sh
$ create-react-native-app my-app --scripts-version=react-native-scripts-ts
$ cd my-app
$ yarn test
```

**Comment by oskogstad** [comment]
Adding this to package.json fixed it:
```js
"jest": {
    "preset": "react-native",
    "transform": {
      "^.+\\.jsx?$": "./node_modules/babel-jest",
      "^.+\\.tsx?$": "ts-jest"
    },
    "testRegex": "(/__tests__/.*|(\\.|/)(test|spec))\\.(jsx?|tsx?)$",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ],
    "globals": {
      "ts-jest": {
        "useBabelrc": true
      }
    }
  }
```

There was no jest entry there after install.

**Comment by mathieudutour** [comment]
ah good catch! Can you send a PR?

**Comment by oskogstad** [comment]
Not had much time to look at it, sorry. I am also new to all this (including programming in general), so would take some time to figure out how stuff works.

**Comment by artyhedgehog** [comment]
Created PR: https://github.com/mathieudutour/create-react-native-app-typescript/compare/master...artyhedgehog:patch-2
Have not tested, though, as don't know how to run create-react-native-app with my modification. Would appreciate guidance in that direction.

**Comment by artyhedgehog** [comment]
Thanks @mathieudutour! 
Got it. Unfortunately, at a first glance I cannot see where to put changes in package.json there. Will try to find out if I have more time.

**Comment by mathieudutour** [comment]
Somewhere here: https://github.com/mathieudutour/create-react-native-app-typescript/blob/master/react-native-scripts/src/scripts/init.js#L76

with something like:
```js
appPackage. jest = {
 ...
}
```

**Comment by binki** [comment]
I tried putting the change in and it seems to be working for me. Unfortunately, this is something that only newly created projects will benefit from—existing ones will require editing `package.json`. I will momentarily create a PR.

One thing I’m doing differently from https://github.com/mathieudutour/create-react-native-app-typescript/issues/7#issuecomment-366471686 (@oskogstad) is using the jest-expo preset instead of react-native preset. Based on the packages specified for `DEFAULT_DEV_DEPENDENCIES`, it seems that the expo preset was intended and, also, expo is more specific and, likely, more appropriate as create-react-native-app targets expo.
